[package]
name = "trouble_audio"
version = "0.1.0"
edition = "2021"

[features]
default = ["defmt"]
defmt = ["dep:defmt", "defmt/alloc", "trouble-host/defmt", "heapless/defmt"]
log = ["dep:log", "embassy-time/log", "trouble-host/log"]

[dependencies]
embassy-sync = "0.8"
embassy-futures = "0.1.1"
embassy-time = "0.5.1"
bt-hci = { version = "0.9", features = ["uuid"] }
embedded-io = "0.7.1"
embedded-io-async = "0.7.0"
trouble-host = { git = "https://github.com/LegitCamper/trouble", rev = "679b3fd7a3d3dca1ad0ea890da0de737cecaef9e", features = [
  "derive",
  "gatt",
  "peripheral",
  "central",
  "scan",
  "security",
  "iso",
  "serde",
  "default-packet-pool",
] }

lc3-codec = "0.2.0"

defmt = { version = "1.0.1", optional = true }
log = { version = "0.4", optional = true }
static_cell = "2.1.0"
heapless = "0.9"
bitflags = "2.8.0"

[patch.crates-io]
embassy-futures = { git = "https://github.com/embassy-rs/embassy.git", rev = "b87c67be691bcb9aa0e1f3813d90d9eb04dd1751" }
bt-hci = { git = "https://github.com/legitcamper/bt-hci", branch = "cis-iso-commands" }
