[package]
name = "trouble-audio-example-apps"
version = "0.1.0"
edition = "2024"

[dependencies]
trouble-host = { git = "https://github.com/embassy-rs/trouble", rev = "0caf63a", features = [
  "derive",
  "gatt",
  "peripheral",
  "scan",
  "security",
  "iso",
  "default-packet-pool",
] }
trouble_audio = { path = "../../trouble-audio", default-features = false }
bt-hci = { version = "0.9", features = ["uuid"] }
embassy-executor = { version = "0.9.1" }
embassy-futures = "0.1.1"
embassy-sync = { version = "0.8" }
embassy-time = "0.5.1"
embedded-hal = "1.0"
static_cell = "2"
embedded-io = "0.7"
heapless = "0.9"
libm = "0.2"

defmt = { version = "1.0.1", optional = true }
log = { version = "0.4", optional = true }

[features]
defmt = [
  "dep:defmt",
  "trouble-host/defmt",
  "trouble_audio/defmt",
  "bt-hci/defmt",
  "embedded-io/defmt",
  "embedded-hal/defmt-03",
]
log = ["dep:log", "trouble-host/log", "trouble_audio/log", "bt-hci/log"]

[patch.crates-io]
embassy-futures = { git = "https://github.com/embassy-rs/embassy.git", rev = "b87c67be691bcb9aa0e1f3813d90d9eb04dd1751" }
bt-hci = { git = "https://github.com/LegitCamper/bt-hci", branch = "cis-iso-commands" }
